services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=osboxes
      - POSTGRES_PASSWORD=osboxes.org
      - POSTGRES_DB=ny_taxi
    volumes:
      - "/home/Projects/docker-container/postgres_db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=osboxes.org
    ports:
      - "8080:80"